# Generated by Django 5.0.7 on 2024-11-25 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Empdetail', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='extenduser',
            name='email',
            field=models.EmailField(default='kishorekumar4735@gmail.com', max_length=254),
        ),
    ]
